#pragma once

#include "commons/base_includes.hpp"
#include "commons/string_includes.hpp"
#include "utils/random_gen.hpp"

#include "corelink_network_constants.hpp"
#include "corelink_data_xchg_protocol.hpp"
#include "corelink_network_global_packet_hold.hpp"

namespace corelink
{
    namespace core
    {
        namespace network
        {
            /**
             * @brief Properties used by IP protocol and its dependant protocols
             */
            struct CORELINK_EXPORT ip_protocol_channel_descriptor
            {
            private:
                /**
                 * @brief Bitmask representing the current channel state
                 */
                std::bitset<sizeof(network::constants::state) * 8> m_channel_state;
            public:
                /**
                 * @brief Randomly generated channel ID. this is generated by the library and should not be changed.
                 */
                channel_id_type channel_id{};
                /**
                 * @brief this is provided by the user to which the communication shall be setup
                 */
                std::string endpoint;
                /**
                 * @brief port number or service name.
                 */
                uint16_t port_number{};
                /**
                 * @brief The type of communication protocol this channel communication uses
                 */
                constants::protocols::protocol protocol;
                /**
                   * @brief The on send callback is called when the data has been transmitted with the number of bytes sent as the
                   * parameter
                   * @details Note that this will only be called if the data was sent successfully.
                   * If there was an error, the on_error callback is invoked instead
                   */
                on_send_type_1 on_send = nullptr;
                /**
                 * @brief The on receive callback is called when there is some data expected to arrive.
                 * Note that this will only be called if the data was sent successfully or if a (half/full)-duplex channel allows
                 * data to be received from a peer.
                 */
                on_receive_type_1 on_receive = nullptr;
                /**
                 * @brief The on error callback is called when there is any form of error during a transaction
                 * @details There are a variety of scenarios where this callback could be called including transaction errors,
                 * improper setup, failed connection, exceptions in some cases.
                 */
                on_error_type_1 on_error = nullptr;

                /**
                 * @brief The on initialized callback is called when there is a initialise operation.
                 * @details This is to provide a standard interface across packet based and stream style protocols depending on IP based protocols.
                 */
                on_init_type_1 on_init = nullptr;

                /**

                 * @brief The on initialized callback is called when there is a un-initialise operation.
                 * @details This is to provide a standard interface across packet based and stream style protocols depending on IP based protocols.
                 */
                on_uninit_type_1 on_uninit = nullptr;

                /**
                 * @brief Set the state of the communication channel with the channel on a bitmask. the positions are marked by the values
                 * of the constants::state enum members
                 * @param state the property to set as defined per the constants::state enum
                 */
                inline lvref<ip_protocol_channel_descriptor> set_state(constants::state state)
                {
                    m_channel_state.set(static_cast<uint8_t>(state));
                    return *this;
                }

                /**
                 * @brief Reset the state of the communication channel with the channel on a bitmask. the positions are marked by the values
                 * @param state the property to reset as defined per the constants::state enum
                 */
                inline lvref<ip_protocol_channel_descriptor> reset_state(constants::state state)
                {
                    m_channel_state.reset(static_cast<uint8_t>(state));
                    return *this;
                }

                /**
                 * @brief Check if the state bit is set for the given state marker
                 * @param state the property to check as defined per the constants::state enum
                 * @return
                 */
                inline bool is_set(constants::state state) const
                { return m_channel_state.test(static_cast<uint8_t>(state)); }

                CORELINK_CPP_ATTR_MAYBE_UNUSED
                inline bool is_state_unknown()
                { return m_channel_state == 0; }

                /**
                 * @brief default constructor
                 */
                explicit ip_protocol_channel_descriptor(
                        const constants::protocols::protocol &p)
                        : protocol(p)
                {}

                /**
                 * @brief copy constructor
                 * @param rhs
                 */
                ip_protocol_channel_descriptor(in<ip_protocol_channel_descriptor> rhs) :
                        endpoint(rhs.endpoint),
                        port_number(rhs.port_number),
                        protocol(rhs.protocol),
                        on_send(rhs.on_send),
                        on_receive(rhs.on_receive),
                        on_error(rhs.on_error),
                        on_init(rhs.on_init),
                        on_uninit(rhs.on_uninit)
                {}

                /**
                 * @brief Move constructor
                 * @param rhs
                 */
                ip_protocol_channel_descriptor(rvref<ip_protocol_channel_descriptor> rhs) noexcept:
                        channel_id(rhs.channel_id),
                        endpoint(std::move(rhs.endpoint)),
                        port_number(rhs.port_number),
                        protocol(rhs.protocol),
                        on_send(std::move(rhs.on_send)),
                        on_receive(std::move(rhs.on_receive)),
                        on_error(std::move(rhs.on_error)),
                        on_init(std::move(rhs.on_init)),
                        on_uninit(std::move(rhs.on_uninit))
                {}

                virtual ~ip_protocol_channel_descriptor() = default;
            };

            /**
             * @brief The IP protocol suite manager
             * @details This class manages all the IP protocol based connections made via the add_channel and init methods.
             * It allows for disconnecting from those endpoints via the teardown function.
             */
            class CORELINK_EXPORT corelink_data_xchg_ip_proto_base
                    : public corelink_data_xchg_protocol
            {
            protected:
                // the map of channels
                std::unordered_map<channel_id_type, std::shared_ptr<ip_protocol_channel_descriptor>> m_channel_descriptors{};

                channel_id_type m_default_channel{};

            public:
                /**
                 * Constructor for the IP based data exchange mechanism
                 */
                corelink_data_xchg_ip_proto_base();

                /**
                 * @brief Copy constructor for the IP proto base
                 * @param rhs const reference to copy from
                 */
                corelink_data_xchg_ip_proto_base(clvref<corelink_data_xchg_ip_proto_base> rhs);

                /**
                 * @brief move constructor for the IP proto base
                 * @param rhs rvalue ref for move from
                 */
                corelink_data_xchg_ip_proto_base(rvref<corelink_data_xchg_ip_proto_base> rhs) noexcept;

                corelink_data_xchg_ip_proto_base &operator=(clvref<corelink_data_xchg_ip_proto_base>);

                corelink_data_xchg_ip_proto_base &operator=(corelink_data_xchg_ip_proto_base &&rhs) noexcept;

                virtual ~corelink_data_xchg_ip_proto_base() = default;

                /**
                 * @brief Add channel details that IP proto base is maintaining
                 * @param channel_descriptor the channel descriptor for the protocol
                 * @return unique channel ID
                 */
                channel_id_type add_channel(std::shared_ptr<ip_protocol_channel_descriptor> &&channel_descriptor);

                /**
                 * @brief Add and initialize the channel.
                 * @param channel_descriptor the channel descriptor for the protocol
                 * @param channel_id the channel ID
                 * @return true if init was okay. False if not
                 */
                bool add_and_init_channel(std::shared_ptr<ip_protocol_channel_descriptor> channel_descriptor,
                                          channel_id_type &channel_id);

                /**
                 * @brief Remove channel record for a given channel ID
                 * @param channel_id channel ID obtained from add_channel
                 */
                void remove_channel(channel_id_type channel_id);

                /**
                 * @brief get the channel. Note that if the requested channel is not found, a default value is a returned.
                 * This default value is internally initialised.
                 * @param channel_id
                 * @return pointer to the channel descriptor
                 */
                std::shared_ptr<ip_protocol_channel_descriptor> &get_channel(channel_id_type channel_id);

                /**
                 * @brief Operator overload for getting channel details from the channel ID
                 * @param channel_id
                 * @return
                 */
                inline std::shared_ptr<ip_protocol_channel_descriptor> operator[](channel_id_type channel_id)
                {
                    return get_channel(channel_id);
                }

                /**
                 * @brief Mechanism whereby derived classes can implement aspects which cannot be done during construction.
                 * each inheriting class has to implement a mechanism specific to the protocol.
                 * If the protocol supports a connection mechanism, then that connection should be made here and not in the
                 * constructor and return an appropriate ret val from this function.
                 * @param channel id
                 * @return true if init was okay. false if not.
                 */
                virtual bool init(channel_id_type channel_id) = 0;

                /**
                 * @brief Mechanism whereby derived classes can implement aspects which cannot be done during construction.
                 * each inheriting class has to implement a mechanism specific to the protocol.
                 * If the protocol supports a connection mechanism, then that connection should be made here and not in the
                 * constructor and return an appropriate ret val from this function.
                 * Initializes all channels which have not been init
                 * @return true if init was okay. false if not.
                 */
                virtual bool init_all()
                {
                    bool ret_val = true;
                    for (auto &channel_impl: m_channel_descriptors)
                        ret_val = ret_val & init(channel_impl.first);
                    return ret_val;
                }

                /**
                 * @brief Mechanism called by the destructor. USER SHOULD NOT CALL THIS FUNCTION EXPLICITLY, IT WILL BE CALLED
                 * by the base class destructor.
                 * @details Note that all files and sockets should be closed here by the user.
                 * put all your de-allocation stuff here.
                 * If the protocol does not support a connection-oriented mechanism, then it is just safe to reclaim resources
                 * and return from this function.
                 *
                 * Note that since this function is called by the destructor, there is no return value. Instead, the on error
                 * mechanism will be triggered in case of an error to guarantee exception safety. It is the users responsibility
                 * to make sure that on_error is initialised properly.
                 */
                virtual void teardown(channel_id_type channel_id) = 0;

                /**
                 * @brief Mechanism called by the destructor. USER SHOULD NOT CALL THIS FUNCTION EXPLICITLY, IT WILL BE CALLED
                 * by the base class destructor.
                 * @details Note that all files and sockets should be closed here by the user.
                 * put all your de-allocation stuff here.
                 * If the protocol does not support a connection-oriented mechanism, then it is just safe to reclaim resources
                 * and return from this function.
                 *
                 * Note that since this function is called by the destructor, there is no return value. Instead, the on error
                 * mechanism will be triggered in case of an error to guarantee exception safety. It is the users responsibility
                 * to make sure that on_error is initialised properly.
                 */
                virtual void teardown_all()
                {
                    for (auto &channel_impl: m_channel_descriptors)
                    {
                        teardown(channel_impl.first);
                    }
                }

                /**
                 * @brief send data: allows for sending data via a data exchange protocol.
                 * This function maybe blocking, but if any async behaviour exists, then the implementing class should
                 * take care of that
                 */
                virtual void send_data(std::vector<uint8_t> &&, channel_id_type) = 0;

                /**
                 * @brief Protocol level error handler
                 */
                std::function<void(const std::string &)> on_protocol_error;
            };
        }
    }
}