/**:
  ros__parameters:
    corelink.endpoint: "corelink.hpc.nyu.edu"
    corelink.port: 20012

    corelink.workspace: "Chalktalk"
    corelink.data_protocol: "udp"

    topic.name: "/chatter"
    topic.type: "std_msgs/msg/String"

    topic.direction: "to_corelink"
    qos: 10 #ros2 quality of service, e.g History/Depth/Reliability/Durability

