apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rtabmap-offload-data
  namespace: hsrn-robot
  labels:
    app: rtabmap-offload

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rtabmap-offload
  namespace: hsrn-robot
  labels:
    app: rtabmap-offload

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rtabmap-offload

  template:
    metadata:
      labels:
        app: rtabmap-offload

    spec:
      containers:
        - name: rtabmap-offload
          image: eddyhu217/offload:2026-07-28
          imagePullPolicy: Always

          env:
            - name: ROS_DOMAIN_ID
              value: "0"

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          volumeMounts:
            - name: rtabmap-data
              mountPath: /root/.ros

      volumes:
        - name: rtabmap-data
          persistentVolumeClaim:
            claimName: rtabmap-offload-data
